### ISSUE TITLE
Integration with Spring Boot and Micrometer

### ISSUE THREAD

**Issue by FilipeCunha720** [stefanprodan/dockprom#127]
I'm trying to see the metrics from a Spring boot application on grafana but I'm not able to see any metrics.

I started my spring application on intellij, and everything is working fine. If I go to [http://localhost:8303/actuator/prometheus](http://localhost:8303/actuator/prometheus) I can  see that the metrics are available.

![screenshot from 2019-02-08 13-43-54](https://user-images.githubusercontent.com/28516131/52481923-c7046e80-2ba7-11e9-990e-a6600affdbf3.png)

I changed `docker-compose.yml` to make it super simple
```
version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.7.1
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    volumes:
#      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  caddy:
    image: stefanprodan/caddy
    container_name: caddy
    ports:
      - "3000:3000"
      - "9090:9090"
    volumes:
      - ./caddy/:/etc/caddy/
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
```

I also changed `prometheus.yml`
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: 'spring-boot'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8303']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']
```

I start the container using `ADMIN_USER=admin ADMIN_PASSWORD=admin docker-compose up -d` and everything works fine.

When I chose the dashboard  *Monitor Services* I can see prometheus data,  but when I download the [Micrometer dashboard](https://grafana.com/dashboards/4701)  everything is empty. 

When I go [http://localhost:9090/grap/](http://localhost:9090/grap/) I can find the prometheus metrics, but the micrometer metrics are not there.

What am I missing? Do I need to change the *Data Source* on Grafana?
