### ISSUE TITLE
How to have proper CPU usage when using multiple remote machines

### ISSUE THREAD

**Issue by darklow** [stefanprodan/dockprom#135]
First of all, thank you for this amazing package. Super useful!
I'm using dockprom to monitor around 10 different remote machines using separate `nodeexporter` and `cadvisor` jobs configs. I've adjusted `Docker Host` dashboard with Grafana templates to switch `jobs` filter and all works great.

However I am having problems with `Docker Containers` dashboard `Container CPU Usage` panel. This panel would be very useful to overview all docker containers from all machines to see any CPU high loads, but right now it is not correct as it uses sum of all CPU usages divided by all CPU available therefore the more machines I added, the less precise chart becomes.

Current expression:
```
sum by (name) (rate(container_cpu_usage_seconds_total{image!="",container_label_org_label_schema_group=""}[1m])) / scalar(count(node_cpu_seconds_total{mode="user"})) * 100
```

Is there any way to adjust this chart so that it still shows all the docker containers from all the machines, but would show CPU usage relative within each machine (per job), not sum of all machines.

Thank you.

**Comment by nightah** [comment]
I do not believe it is possible to show you all of the containers within the same panel with CPU usage relative to each machine. 

Obviously you could use variables and template that single panel so as you adjust the instance it updates that panel.

Perhaps add a variable named `Host` and similar to your jobs filter modify the Dashboard query to something like this:
`sum by (name) (rate(container_cpu_usage_seconds_total{image!="",container_label_org_label_schema_group="",instance="$host"}[1m])) / scalar(count(node_cpu_seconds_total{mode="user"})) * 100`

Another alternative might be to do a repeating panel based on a variable and that way you get a Container CPU Usage panel per instance too.

**Comment by darklow** [comment]
Thanks for the help, unfortunately adding "jobs" to that query doesn't help as it keeps showing CPU usage against total node_cpu_seconds_total from all machines.
Ended up duplicating query 10x times using each job name per query, not best, but at least it works and I have single chart to spot any sudden CPU issues in any of machines. I wish there could be a way to iterate over template variables in single query or some kind of group by "jobs" feature.

**Comment by nightah** [comment]
@darklow sorry you're right, just adjust the query though:
`sum by (name) (rate(container_cpu_usage_seconds_total{image!="",container_label_org_label_schema_group="",instance="$host:8080"}[1m])) / scalar(count(node_cpu_seconds_total{instance="$host:9100",mode="user"})) * 100`

Assuming your `prometheus/prometheus.yml` looks something like this, due to multiple hosts and instances of nodeexporter/cadvisor:
```yml
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.10.1:9100']
      - targets: ['10.10.10.2:9100']
      - targets: ['10.10.10.3:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.10.1:8080']
      - targets: ['10.10.10.2:8080']
      - targets: ['10.10.10.3:8080']
```
You will need to strip the port from your template variable `$host` so you select based on hostname or IP alone and this will adjust the query accordingly.
Might need to use regexes to strip the port suffix for your `$host` variable though.
