### ISSUE TITLE
cadvisor        | W0724 15:22:31.424121       1 fs.go:556] stat failed on /dev/sdc1 with error: no such file or directory

### ISSUE THREAD

**Issue by gerroon** [stefanprodan/dockprom#153]
Hi
I am trying to set this up. The only thing I did was to change the external ports from Caddy in the compose file. 

Does anyone know anything about the error in the title?

I am using it on Debian Testing.

thanks

**Comment by nightah** [comment]
Can you please confirm the exact lines and what you have changed?
Also what filesystem is running on the host system?

**Comment by gerroon** [comment]
`/var/lib/docker` is symlinked to another drive because I do not have enough large space on the system drive for all those docker images. 

Sys drive is ext4
One the actual docker folder is btrfs (/dev/sdc1)

Bear in mind that I have 10s of docker apps running using the same setup, none of them seems to have any issues.

```
      - "6010:3000"                                                                                                                                                                                                
      - "6090:9090"                                                                                                                                                                                                
      - "6093:9093"                                                                                                                                                                                                
      - "6091:9091"
```

**Comment by nightah** [comment]
Can you try explicitly volume mount your /var/lib/docker folder as opposed to allow it to follow the symlink?

**Comment by gerroon** [comment]
Well, maybe but not for a while because that means that I need to stop all my services :(

**Comment by nightah** [comment]
Sorry I think you misunderstood what I meant.

Let's say your your symlink of /var/lib/docker points to /mnt/docker, change the volume mapping for cadvisor (specifically https://github.com/stefanprodan/dockprom/blob/0de10968cbca35954a9b39b630e80313c987c28d/docker-compose.yml#L77) to point to `/mnt/docker:/var/lib/docker:ro`

**Comment by gerroon** [comment]
Ok, tried it and that did not make a diff :(

**Comment by nightah** [comment]
Can you please post the full cadvisor logs?

**Comment by gerroon** [comment]
The log is literally filled with that error thousands of lines after couple minutes, so I tried to get from the top

https://bin.privacytools.io/?f7b12f72d2c93d70#Hzm8xMvNeXA2yy+g0fqxrBVUn/a3Q42L4qX0fZMc+CQ=

**Comment by nightah** [comment]
You need to pass in your devices so to get disk stats, below is my cadvisor block.
Add your own devices in as you see fit to be able to gather stats.

```
  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    devices:
      - /dev/zfs:/dev/zfs
      - /dev/kmsg:/dev/kmsg
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
```
