### ISSUE TITLE
Cannot start service cadvisor: listen tcp 0.0.0.0:9093: bind: address already in use

### ISSUE THREAD

**Issue by andrewssobral** [stefanprodan/dockprom#157]
Hi,
`dockprom` was working fine in our server, but now, after rebooting the PC and pushing the last commits, I have this:
```
user@server:~/monitoring/dockprom$ ADMIN_USER=admin ADMIN_PASSWORD=admin docker-compose up -d
Creating network "dockprom_monitor-net" with driver "bridge"
Creating cadvisor     ... error
Creating nodeexporter ... 
Creating caddy        ... 
Creating grafana      ... 
Creating caddy        ... error
Creating pushgateway  ... 
Creating nodeexporter ... done

Creating grafana      ... done
Creating prometheus   ... done
Creating pushgateway  ... done
Creating alertmanager ... done

ERROR: for caddy  Cannot start service caddy: driver failed programming external connectivity on endpoint caddy (41431f8005c71d44b06a8525eb40508791abf0f37982e01d8c89a75f2dd8185d): Error starting userland proxy: listen tcp 0.0.0.0:9093: bind: address already in use

ERROR: for cadvisor  Cannot start service cadvisor: error while creating mount source path '/var/lib/docker': mkdir /var/lib/docker: read-only file system
ERROR: Encountered errors while bringing up the project.
```
more info:
```
user@server:~/monitoring/dockprom$ docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
5bfe75a2d7dd        grafana/grafana:6.2.5        "/setup.sh"              58 seconds ago      Up 56 seconds       3000/tcp            grafana
fc043e7d576f        prom/alertmanager:v0.18.0    "/bin/alertmanager -…"   58 seconds ago      Up 53 seconds       9093/tcp            alertmanager
ad185595a0dd        prom/pushgateway:v0.9.0      "/bin/pushgateway"       58 seconds ago      Up 54 seconds       9091/tcp            pushgateway
d4f7715d661e        stefanprodan/caddy           "/sbin/tini -- caddy…"   58 seconds ago      Created                                 caddy
df1aad89f777        prom/prometheus:v2.11.1      "/bin/prometheus --c…"   58 seconds ago      Up 55 seconds       9090/tcp            prometheus
95811735cb09        prom/node-exporter:v0.18.1   "/bin/node_exporter …"   58 seconds ago      Up 56 seconds       9100/tcp            nodeexporter
f1a0dbc3a3a5        google/cadvisor:v0.33.0      "/usr/bin/cadvisor -…"   58 seconds ago      Created             8080/tcp            cadvisor
```

**Comment by nightah** [comment]
It looks to me like you have modified your `docker-compose.yml` to expose caddy to port 9093 on the host and that port appears to already be in use.

Can you paste your full `docker-compose.yml` and the output of `sudo lsof -i :9093`?

**Comment by andrewssobral** [comment]
Thank you @nightah  for your feedback,
It's strange, because my docker-compose.yml was not modified as you can see in my git status:
```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        run.sh

nothing added to commit but untracked files present (use "git add" to track)
```
I've just added a bash script containing:
```
ADMIN_USER=admin ADMIN_PASSWORD=admin docker-compose up -d
```

Here's the contents of my docker-compose:
`cat docker-compose.yml`
```
version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.12.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  alertmanager:
    image: prom/alertmanager:v0.18.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:v0.18.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:6.3.3
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  pushgateway:
    image: prom/pushgateway:v0.9.1
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  caddy:
    image: stefanprodan/caddy
    container_name: caddy
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
      - "9091:9091"
    volumes:
      - ./caddy/:/etc/caddy/
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
```

`sudo lsof -i :9093`
```
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
docker-pr 2881 root    4u  IPv6  36138      0t0  TCP *:9093 (LISTEN)
```

`sudo netstat -pna | grep 9093`
```
tcp6       0      0 :::9093                 :::*                    LISTEN      2881/docker-proxy   
```

`docker ps -a`
```
CONTAINER ID        IMAGE                        COMMAND                  CREATED              STATUS              PORTS               NAMES
741ceac72462        grafana/grafana:6.3.3        "/setup.sh"              About a minute ago   Up About a minute   3000/tcp            grafana
333beb895cc0        prom/node-exporter:v0.18.1   "/bin/node_exporter …"   About a minute ago   Up About a minute   9100/tcp            nodeexporter
ea98e5472c81        prom/alertmanager:v0.18.0    "/bin/alertmanager -…"   About a minute ago   Up About a minute   9093/tcp            alertmanager
8b5f5129012a        prom/pushgateway:v0.9.1      "/bin/pushgateway"       About a minute ago   Up About a minute   9091/tcp            pushgateway
bd54ce4e7806        stefanprodan/caddy           "/sbin/tini -- caddy…"   About a minute ago   Created                                 caddy
52609461a3c2        prom/prometheus:v2.12.0      "/bin/prometheus --c…"   About a minute ago   Up About a minute   9090/tcp            prometheus
37d4ddd2016a        google/cadvisor:v0.33.0      "/usr/bin/cadvisor -…"   About a minute ago   Created             8080/tcp            cadvisor
```
