### ISSUE TITLE
Correctly setup smtp with grafana

### ISSUE THREAD

**Issue by t-book** [stefanprodan/dockprom#169]
Hi Stefan,

thanks for the great stack! One question. Could you kindly help where to start enabling sending reports by smtp? From what I read therefore the alertmanager has to be configured. This is what I did:

```
docker@localhost:/opt/dockprom$ cat alertmanager/config.yml 
global:
  smtp_smarthost: smtp.mail.de:25
  smtp_from: XXX
  smtp_auth_username: XXX
  smtp_auth_password: XXX
  smtp_require_tls: true

route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#<channel-name>'
            api_url: 'https://hooks.slack.com/services/<webhook-id>'
```

However, after rebuilding the container, grafana keeps saying that grafana.ini is missing smtp settings. 

thanks for your help!

**Comment by nightah** [comment]
Here's a redacted copy of my alertmanager `config.yml` with SMTP configuration:
```
route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#<channel-name>'
            api_url: 'https://hooks.slack.com/services/<webhook-id>'
    - name: 'email'
      email_configs:
          - send_resolved: true
            to: 'alertmanager@example.com'
            from: '"Alertmanager" <alertmanager@example.com>'
            smarthost: 'mail.example.com:25'
            auth_username: 'user@example.com'
            auth_password: 'SECUREPASSWORD'
            html: '{{ template "email.default.html" . }}'
```
