### ISSUE TITLE
Monitoring of remote hosts

### ISSUE THREAD

**Issue by kryvel** [stefanprodan/dockprom#171]
Hi,
Thank you for creating such great toolstack 

I've started with connecting remote machines to my dockprom instance.
Now I have following prometheus config
```
...
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'nodeexporter:9100'
        - 'serv1:9100'

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'cadvisor:8080'
        - 'serv1:8080'
...
```

On remote machine serv1 are running containers from docker-compose.exporter.yml

But I have no idea what next ? How could I display data from remote hosts ?
Should I manually create Dashoboard configs ? Or maybe there are some templates or how-tos ?

On remote machines there are mostly docker hosts, but also I would like to monitor Xen hypervisors, mail servers, simple hosts etc.

TIA
