### ISSUE TITLE
Use different network interface

### ISSUE THREAD

**Issue by jrarseneau** [stefanprodan/dockprom#18]
Hello,

Newer versions of Ubuntu will often have different network interface names (instead of eth0, it'll be something like enp1s0f0).

By default, if this is the case, the network monitor doesn't show any traffic and I'm afraid I can't figure out how to change this.

Could you shed some light please?

Thanks.

**Comment by k-s-dean** [comment]
In the docker-compose.yml, change the following. 


   ```
    ports:
      - 9090:9090
```

to 

```
    ports:
      - "192.168.0.1:9090:9090"
```

So specify the IP of the interface you wish your containers to bind to. 

```
    ports:
      - "<YOUR enp1s0fo IP>9090:9090"
```
hope that helped 

kind regards.

**Comment by johnbritto1** [comment]
The fix isn't working.  The Network Usage graphs of "Docker Host" in grafana doesn't show any traffic update.  Please help.

**Comment by nightah** [comment]
There's two elements that need to change to achieve this.
The default `docker-compose.yml` monitors the ethernet interface of the node_exporter instance (which isn't your host).

Alternatively you could run the node_exporter instance in the `docker-compose.exporters.yml` file:

```yaml
nodeexporter:
    image: prom/node-exporter:v0.17.0
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - 9100:9100
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"
```

Or modify your default `docker-compose.yml` to reflect the host interface like such:
```yaml
nodeexporter:
    image: prom/node-exporter:v0.17.0
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"
```

After this change you then need to modify your Docker Host Grafana dashboard to reflect the actual ethernet interface on your host. For example mine is `eno1` so the following:
- `irate(node_network_receive_bytes_total{device="eth0"}[1m])`
- `irate(node_network_transmit_bytes_total{device="eth0"}[1m])`

Should read:

- `irate(node_network_receive_bytes_total{device="eno1"}[1m])`
- `irate(node_network_transmit_bytes_total{device="eno1"}[1m])`
