### ISSUE TITLE
Use nginx scrape for prometheus

### ISSUE THREAD

**Issue by kekedaine** [stefanprodan/dockprom#187]
Please guide me to use nginx scrape for prometheus.
I need use nginx dashboard in grafana

thanks you so much

![dainv 2020-06-30 at 23 45 47](https://user-images.githubusercontent.com/4715657/86153440-e0ef7a00-bb2b-11ea-9ffe-c3814f27cfcc.JPG)

.

**Comment by nightah** [comment]
you need to add the nginxexporter to your `docker-compose.yml`:

```yaml
  nginxexporter:
    image: fish/nginx-exporter
    container_name: nginxexporter
    command:
      - '-nginx.scrape_uri=https://example.com/nginx_status'
    restart: unless-stopped
    expose:
      - 9113
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
```

You also need to ensure that you're exporting the stub status on the endpoint you put inside `-nginx.scape_uri`:

```nginx
    location /nginx_status {
        stub_status on;
        access_log off;
        allow 172.0.0.0/8;
        deny all;
    }
