### ISSUE TITLE
Not able to receive resolved alerts in slack

### ISSUE THREAD

**Issue by johnreytanquinco** [stefanprodan/dockprom#194]
I have configured alert manager to send alerts in slack. I was able to send failure alerts but not the resolved ones. For example, I have a `container_wordpress_down` rule, I stop the container, and I receive the failure alert. I started back wordpress and according to my `http://<host-ip>:9093`, it was already resolved but haven't receive the resolved alert to slack.
```
route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
...
```
As expected the above config should satisfy the condition and should be able to send resolved alert or am I missing something? Hope someone can help. Thanks!
