### ISSUE TITLE
Scrape wordpress metrics

### ISSUE THREAD

**Issue by rgg1993** [stefanprodan/dockprom#202]
HI!

I've been trying to scrape wordpress metrics, but haven't been able to do. 
May be you could help me out; I've the following code: 

--Updated docker-compose.yml with mysql db and wordpress: 
```

version: "2.1"
networks:
  monitor-net:
    driver: bridge
volumes:
  prometheus_data: {}
  grafana_data: {}
  db_data: {}

services:
  db:
    container_name: mascotas_unidas_mysql
    image: "mysql:${MYSQL_CONT_VERSION}"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
    env_file:
      - ./env.dev
    networks:
      - monitor-net
    labels:
      org.label-schema.group: monitoring

  wordpress:
    container_name: mascotas_unidas_wordpress
    depends_on:
      - db
    image: "wordpress:${WORDPRESS_CONT_VERSION}"
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 8000
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
    env_file:
      - ./env.dev
    networks:
      - monitor-net
    labels:
      org.label-schema.group: monitoring

  prometheus:
    image: "prom/prometheus:v2.22.2"
    container_name: prometheus
    volumes:
      - "./prometheus:/etc/prometheus"
      - "prometheus_data:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: monitoring

  alertmanager:
    image: "prom/alertmanager:v0.21.0"
    container_name: alertmanager
    volumes:
      - "./alertmanager:/etc/alertmanager"
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: monitoring

  nodeexporter:
    image: "prom/node-exporter:v1.0.1"
    container_name: nodeexporter
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - >-
        --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
    restart: unless-stopped
    depends_on:
      - wordpress
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: monitoring

  cadvisor:
    image: "gcr.io/cadvisor/cadvisor:v0.38.4"
    container_name: cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
    restart: unless-stopped
    depends_on:
      - wordpress
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: monitoring

  grafana:
    image: "grafana/grafana:7.3.3"
    container_name: grafana
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    environment:
      - "GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}"
      - "GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}"
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: monitoring

  pushgateway:
    image: "prom/pushgateway:v1.3.0"
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitor-net
    labels:
      org.label-schema.group: monitoring

  caddy:
    image: stefanprodan/caddy
    container_name: caddy
    ports:
      - "8000:8000"
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
      - "9091:9091"
    volumes:
      - "./caddy:/etc/caddy"
    environment:
      - "ADMIN_USER=${ADMIN_USER:-admin}"
      - "ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}"
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: monitoring


```

--- Updated Caddyfile with wordpress
```

:9090 {
    basicauth / {$ADMIN_USER} {$ADMIN_PASSWORD}
    proxy / prometheus:9090 {
            transparent
        }

    errors stderr
    tls off
}

:9093 {
    basicauth / {$ADMIN_USER} {$ADMIN_PASSWORD}
    proxy / alertmanager:9093 {
            transparent
        }

    errors stderr
    tls off
}

:9091 {
    basicauth / {$ADMIN_USER} {$ADMIN_PASSWORD}
    proxy / pushgateway:9091 {
            transparent
        }

    errors stderr
    tls off
}

:3000 {
    proxy / grafana:3000 {
            transparent
            websocket
        }

    errors stderr
    tls off
}

:8000 {
    proxy / wordpress:80 {
            transparent
            websocket
        }

    errors stderr
    tls off
}

```

-Updated prometheus.yml to scrape the metrics: 

```

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: "wordpress"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "nodeexporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "pushgateway"
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

```

Still, when logging to localhost:9090/targets, I have the following error: 

![image](https://user-images.githubusercontent.com/70332427/100275998-9a1d7900-2f3f-11eb-962f-a700472a2a19.png)

I've tried with several different solutions, as adding a daemon.json to etc/docker; modifiying the localhost:8000 at prometheus..yml; but nothing seems to work. 

I'd really appreciate if you could help me out. 

Thanks!

Rosina

**Comment by nightah** [comment]
I don't really know anything about the wordpress metrics that you're trying to scrape but I noticed an issue with your `prometheus.yml` you're not actually trying to pull metrics from wordpress you're trying to pull them locally from prometheus which is incorrect.

The following is what you need to update your wordpress scape job to:

```yml
scrape_configs:
  - job_name: "wordpress"
    scrape_interval: 5s
    static_configs:
      - targets: ["wordpress:80"]
```

**localhost -> wordpress** also the port should be the port that wordpress is exposing in the container not what you have proxied through caddy.

Hope this helps!
