### ISSUE TITLE
Add memory limits

### ISSUE THREAD

**Issue by pascalandy** [stefanprodan/dockprom#22]
Are you interested to add memory limits?

Something like:
```
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 192M
        reservations:
          memory: 96M
```

If yes, I'll do a PR.
Cheers!
