### ISSUE TITLE
Can't connect to nodeexporter locally

### ISSUE THREAD

**Issue by copolycube** [stefanprodan/dockprom#234]
Hello, 

There are 2 nodeexporter definitions
- (A) 1 in docker-compose.yml
- (B) 1 in docker-compose.exporter.yml

If I use (A), and defined the scraping at prometheus, it connects, but doesn't show the local filesystem data.

If I use (B), I am able to curl it from the command line, but it fails to be scraped (tried with the `nodeexporter:9100` container name, with `localhost:9100`  and with the server name `http://<url>:9100` ) from prometheus.yml but none work and it is still seen as beeing down.

I'm surely missing a obvious piece there, but I can't figure it, any insights would be great !

Thanks in advance for your help

**Comment by nightah** [comment]
You've assumed correctly that if using B you need to update the definition in the `prometheus.yml` to point to the host as opposed to the container name.

If the hostname doesn't work try utilising the IP address of the host, there could be a DNS resolution problem occuring.

So for example if your IP of the host was `10.10.10.1` you would have the following:

```
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.10.1:9100']
```
