### ISSUE TITLE
No data in grafana dashboard

### ISSUE THREAD

**Issue by rugleb** [stefanprodan/dockprom#248]
Hello everyone!
Grafana displays "No Data" on panels in every dashboard like this:

<img width="1701" alt="Снимок экрана 2021-11-30 в 01 59 45" src="https://user-images.githubusercontent.com/26823697/143956188-738b825b-30d3-469f-bfb3-704e2b8ae841.png">

My stack:

docker-compose.yml
```yml
version: "3.8"

services:

  my_app_api:
    image: my_app
    container_name: my_app_api
    env_file:
      - .env
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    networks:
      - my_app_network

  k6:
    image: loadimpact/k6:0.35.0
    container_name: k6
    env_file:
      - .env
    environment:
      - FAKE_NCB_URL=http://my_app_api:8080
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - K6_INFLUXDB_PUSH_INTERVAL=5s
    volumes:
      - ./k6.js:/k6.js
      - ./data:/data
    command: run /k6.js
    depends_on:
      - my_app_api
      - influxdb
    networks:
      - my_app_network

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      - INFLUXDB_DB=k6
    networks:
      - my_app_network

  prometheus:
    image: prom/prometheus:v2.31.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/prometheus.yml
    command:
      - "--config.file=/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor
    networks:
      - my_app_network

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100
    networks:
      - my_app_network

  grafana:
    image: grafana/grafana:8.2.5
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning
    depends_on:
      - influxdb
      - prometheus
    networks:
      - my_app_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.43.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    ports:
      - "8000:8080"
    networks:
      - my_app_network

networks:
  my_app_network:
    name: my_app_network
```

promethteus.yml
```yml
global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
```

I use [this configuration](https://github.com/stefanprodan/dockprom/tree/master/grafana/provisioning) of grafana.

In the grafana requests I see promql requests like this:
```promql
sum by (name)(container_memory_usage_bytes{image!="",container_label_org_label_schema_group=""})
```

But `container_memory_usage_bytes` dont have the `image` label:

<img width="1190" alt="Снимок экрана 2021-11-30 в 01 55 36" src="https://user-images.githubusercontent.com/26823697/143955684-7e62e4b9-f3bc-4300-984b-0c48449e32c4.png">

What's wrong with my stack?
Thanks
