### ISSUE TITLE
nodeexporter container should utilize "host" networking driver to also collect host level network metrics

### ISSUE THREAD

**Issue by Kami** [stefanprodan/dockprom#250]
Right now ``nodeexporter`` and other containers as part of this deployment utilize ``bridge`` network driver.

Even though ``/`` host file system is mounted into this container, network interface metrics will only be collected for the nodeexporter container and not for host.

The reason for that is that ``/proc/net -> self/net`` is a symlink which gets resolved to ``self/net`` inside the container which means only container metrics will be retrieved.

To also collect metrics for other host interfaces, the easiest approach is to change network type to ``host``:

```yaml
  nodeexporter:
    image: prom/node-exporter:v1.3.0
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
...
    restart: unless-stopped
    expose:
      - 9100
    ports:
      - 127.0.0.1:9100:9100
    # We run it in host network mode so we get access to metrics for all the
    # interfaces
    network_mode: host
```

And then prometheus config also needs to be updated to utilize internal IP for the nodeexporter target.

For example:

```yaml
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 30s
    static_configs:
      #- targets: ['nodeexporter:9100']
      # If network_mode host is used for node exporter, we need to use host
      # internal IP
      - targets: ['192.168.168.10:9100']
```

If there are no objections, I will open a PR which explains this in the readme.
