### ISSUE TITLE
Monitor metrics endpoints on services

### ISSUE THREAD

**Issue by elliots** [stefanprodan/dockprom#34]
I'm trying to get the prometheus configured here to scrape the metrics endpoints of the containers, not just the stats coming from cadvisor. Maybe finding them via a label?

Just wondering if you've seen or done something similar. 

Cheers,
E.

**Comment by elliots** [comment]
I ended up getting this working great using dns-sd... if its useful to put, add to in the docs (or for anyone googling..)

Before starting dockprom I add a little extra to the config

```bash
    echo "
  - job_name: 'services'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - scrape.me.prometheus
        type: 'A'
        port: 9999
    " >> prometheus/prometheus.yml
```

Then, on each of my services in docker-compose that I want to be monitored i provide the metrics at ":9999/metrics" and add the right alias...

```yaml
  my-service:
    image: "super-special-service:latest"
    networks:
      default:
        aliases:
         - scrape.me.prometheus
```

And add prometheus to the network docker-compose made for my app....

```bash
docker network connect myapp_default prometheus
```

And, done!

**Comment by stefanprodan** [comment]
Your config is similar to what I've used for Docker Swarm in this project (swarmprom)[https://github.com/stefanprodan/swarmprom].

How will you differentiate the services since the job name will be the same for all? The containers IPs will change after each deploy.

**Comment by elliots** [comment]
Hmm. I... don't know. Something fun to play with next.

**Comment by stefanprodan** [comment]
My approche was this https://github.com/stefanprodan/swarmprom#monitoring-applications-and-backend-services

**Comment by albertorm95** [comment]
Hello, I have a question, I have multiple services from the same web application but each is a different environments, I'm using this config:
```
  - job_name: 'app'
    metrics_path: /services/app/metrics
    scheme: https
    scrape_interval:  5s
    tls_config:
      insecure_skip_verify: true
    dns_sd_configs:
    - names:
      - 'tasks.app'
      type: 'A'
      port: 443
```
How can I get like a Swarm Service Label || Container Label || Task Label in order to differentiate each task?
