### ISSUE TITLE
is it possible to monitor containers inside another server? 

### ISSUE THREAD

**Issue by rischanlab** [stefanprodan/dockprom#5]
Hi @stefanprodan 

It seems this is not an issue. 
I am just following your blog post to deploy this project and it's very nice.

I have a case that I need to install Prometheus only on one server and is it possible to monitor all containers inside another server? maybe by adding source "IP from another server" which previously we install a Prometheus client on that server. 

Thank you

**Comment by stefanprodan** [comment]
There is no Prometheus client, maybe you are referring to cAdvisor?

**Comment by rischanlab** [comment]
Not sure, I am really new with Prometheus. 

I just have a case:

I have many server just call it tree servers (A,B, and C). all servers running with Ubuntu. 
Each server has many running docker containers. I want to monitor all containers on those all servers. 

But I want to centralise all monitoring stuff on one server. So, I add one server (D) then I deploy this project on this server. I want to monitor all docker containers inside all servers (A,B, and C) only from server D. 

Could I use this project to do that? 
On your article you said 

> Dockprom Grafana dashboards can be easily extended to cover more then one Docker host. In order to monitor more hosts, all you need to do is to deploy a node-exporter and a cAdvisor container on each host and point the Prometheus server to scrape those.


But really I am still not able to understood that statement. 

Thank you,

**Comment by stefanprodan** [comment]
You need to deploy node-exporter and cAdvisor containers on all servers you want to monitor. Add the node-exporter and cAdvisor addresses to the Prometheus config. See this [issue](https://github.com/stefanprodan/dockprom/issues/4) for more details.

**Comment by rischanlab** [comment]
Thank you @stefanprodan will try that.
But is there any issue or references about how to deploy node-exporter and cAdvisor?

**Comment by stefanprodan** [comment]
I've made a compose file for you. You can run that compose on the hosts you want to monitor and add those hosts IPs in the Prometheus config.

**Comment by rischanlab** [comment]
Thank you @stefanprodan for this help. 

I used difference way and it works. 

I run this project to all servers. (Including Prometheus service not only cAdvisor and node-exporter)
Then I added multiple data sources inside the master server. (I added Prometheus URL like http://IP-server:9090 ) 
I added the templates according to data source then I load all templates to the dashboard and everything working fine. 

Anyway thank you for your commit

**Comment by stefanprodan** [comment]
Nice! I'm glad you sorted out, I'm closing this issue then.

**Comment by JeromeVi** [comment]
Hi @stefanprodan, @rischanlab 
I'm trying to do that too but I'm stuck with the 

> add those hosts IPs in the Prometheus config

In the folder Prometheus I have 3 files.rules and prometheus.yml. And the config file is the `.yml` but where I should add the ip ? Because I have deployed `cAdvisor` and `nodeexporter`  on my hosts and the ip is 192.168.99.100.

```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "targets.rules"
  - "host.rules"
  - "containers.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

```
