### ISSUE TITLE
External host/containers monitoring?

### ISSUE THREAD

**Issue by ScottBrenner** [stefanprodan/dockprom#52]
I'm new to the wonderful world of containers and am having difficulty deploying this to monitor external hosts/nodes. How can I monitor additional hosts/containers beyond what this is deployed on? Maybe a more in-depth version of [this comment](https://github.com/stefanprodan/dockprom/issues/34#issuecomment-339791812).

**Comment by stefanprodan** [comment]
Deploy `docker-compose.exporters.yml` on an external host and in your Prometheus config add the hostname or the IP like this: 

```yaml
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100','external_host1_ip:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080','external_host1_ip:8080']
```
