### ISSUE TITLE
Nginx reverse proxy before Grafana?

### ISSUE THREAD

**Issue by Saboteur777** [stefanprodan/dockprom#81]
Hey, is it possible to use https://github.com/jwilder/nginx-proxy before grafana gets hit by the request? If yes, what should be the right direction in configuration: nginx should proxy caddy and its 3 ports (on which the different services ports get exposed), or I should proxy the services directly?

**Comment by enric1994** [comment]
Same problem here, any idea to proxy Grafana with Jwilder reverse proxy?

**Comment by enric1994** [comment]
I did the following approach and it works:
```
grafana:
    image: grafana/grafana:4.6.3
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - VIRTUAL_HOST=monitor
      - VIRTUAL_PORT=3000

    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
    restart: always
    networks:
      - monitor-net
```
I deleted the caddy container and I proxied the grafana container directly using the `VIRTUAL_PORT=3000`
